version: "3.10"

services:
 db:
   image: postgres:13.3
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USER}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5433:5433"
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/shop
   ports:
     - "8000:8000"
   depends_on:
     - db
volumes:
  postgres_data:
